config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'posts#index'
  resources :users do
    member do
      get 'item'
      get 'like'
      get :following, :followers
    end
  end
  resources :follow_relationships, only: [:create, :destroy]
  resources :items do
    collection do
      get 'search'
    end
    collection do
      get 'locate'
    end
    resources :reviews, only: [:index,:create,:destroy]
  end
  resources :posts do
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :comments, only: [:create,:destroy,]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post#, counter_cache: :likes_count
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:create, :destroy]

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    @like.destroy
  end

  private

  def set_like
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_favorite.html.erb
<div class="posts-like-btn">
  <% if user_signed_in? %>
    <% if post.like_user(current_user.id)  %>
      <%= link_to post_likes_path(post),method: :delete,class:"like-btn", remote: true do %>
        <i class="fas fa-heart icon-herat-red"></i>
        <%= post.likes.count %>
      <% end %>
      <% else %>
      <%= link_to post_likes_path(post),method: :post,class:"like-btn", remote: true do %>
        <i class="far fa-heart icon-herat-gray"></i>
        <%= post.likes.count %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/likes/_like.html.erb
<div class="posts-like-btn">
  <% if user_signed_in? %>
    <% if post.like_user(current_user.id) %>
      <%= link_to post_likes_path(@post),method: :delete,class:"like-btn",remote: true do %>
        <i class="fas fa-heart icon-herat-red"></i>
        <%= @post.likes.count %>
      <% end %>
      <% else %>
      <%= link_to post_likes_path(@post),method: :post,class:"like-btn",remote: true do %>
        <i class="far fa-heart icon-herat-gray"></i>
        <%= @post.likes.count %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/likes/create.js.erb
$('#like-of-<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#like-of-<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");