config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'posts#index'
  resources :users do
    member do
      get 'item'
      get 'like'
      get :following, :followers
    end
  end
  resources :follow_relationships, only: [:create, :destroy]
  resources :items do
    collection do
      get 'search'
    end
    collection do
      get 'locate'
    end
    resources :reviews, only: [:index,:create,:destroy]
  end
  resources :posts do
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :comments, only: [:create,:destroy,]
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_home.html.erb
<%= link_to root_path do %>
  <p class="back-home-btn">
    <i class="fas fa-home"></i>
    HOME
  </p>
<% end %>

app/views/shared/_items.html.erb
<%= link_to items_path do %>
  <p class="back-home-btn">
    <i class="fas fa-arrow-left"></i>
    アイテム一覧に戻る
  </p>
<% end %>

app/views/shared/_items_header.html.erb
<header>
  <div class="top-main-box">
    <div class="top-main-parent">
      <div class="header-logo-mark"><%= link_to "like-bike", root_path,method: :get %></div>
      <div class="posts-lists"><%= link_to "投稿一覧", posts_path,method: :get, class: "main-menu" %></div>
      <div class="items-lists"><%= link_to "アイテム一覧", items_path %></div>
      <div class="seach-form-box">
        <%= form_with(url: locate_items_path, local: true, method: :get, class: "search-form-content") do |form| %>
        <%= form.text_field :keyword, placeholder: "アイテムを検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
        <% if user_signed_in? %>
          <div class="posts-new-action">
            <%= link_to "新規投稿", new_post_path,method: :get %>
          </div>
          <div class="items-new-action">
            <%= link_to "アイテムを投稿", new_item_path,data: {"turbolinks"=>false} %>
          </div>
          <div class="user-action-logout">
            <%=link_to "ログアウト",  destroy_user_session_path,method: :delete, class: "logout" %>
          </div>
          <% else %>
           <div class="header-guesto-login"><%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post,class:"btn-header-guest-login" %></div>
           <div class="user-action-login"><%= link_to "ログイン", new_user_session_path, class: "header-login-btn" %></div>
           <div class="user-action-new"><%= link_to "ユーザー登録", new_user_registration_path,method: :get, class: "new-user" %></div>
        <% end %>
    </div>
  </div>
</header>

app/views/shared/_left_box.html.erb
<div class="left-box">
  <div class="user-profile-box">
    <div class="user-profile-image-name">
      <div class="user-profile-image"><%= image_tag @user.image.variant(resize: '70x70'), class: "post-user-img" if @user.image.attached? %></div>
      <div class="user-name-info">
        <div class="user-name-info-text">ユーザー名</div>
        <p class="user-profile-name"><%= @user.nickname %></p>
      </div>
    </div>
    <div class="user-profile-info-text">プロフィール</div>
    <div class="user-profile-text"><%= @user.profile %></div>
  </div>
  <div class="user-details">
    <%= link_to user_path do %>
      <div class="user-show-action">
        <i class="far fa-file-alt"></i>
        <%= "#{@nickname}さんの投稿を見る" %>
      </div>
    <% end %>
    <%= link_to item_user_path do %>
      <div class="user-show-action">
        <i class="fas fa-glasses"></i>
        <%= "#{@nickname}さんのアイテムを見る" %>
      </div>
    <% end %>
    <%= link_to like_user_path do %>
      <div class="user-show-action">
        <i class="fas fa-bookmark"></i>
         <%= "#{@nickname}さんのいいねを見る" %>
      </div>
    <% end %>
    <div class="following-follower-count">
      <div class="following-count"><%= link_to "フォロー(#{@user.followings.count})", following_user_path(@user), class: "nav-link" %></div>
      <div class="follower-count"><%= link_to "フォロワー(#{@user.followers.count})", followers_user_path(@user), class: "nav-link" %></div>
    </div>
    <% if user_signed_in? && @user != current_user%>
      <div id="follow_form">
        <% if current_user.following?(@user) %>
          <%= render "unfollow" %>
          <% else %>
          <%= render "follow" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_list_follow.html.erb
<div class="list-posts">
  <% @users.each do |user| %>
    <div class="post-index">
      <%= link_to user_path(user) do %>
        <div class="follower-users">
          <div class="follower-user-nickname-image">
            <%= image_tag user.image.variant(resize: '60x60'), class: "follower-user-img" if user.image.attached? %>
            <div class="follower-user-nickname"><%= user.nickname %></div>
          </div>
          <p class="follower-user-perofile"><%= user.profile %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_list_items.html.erb
<div class="list-posts">
  <% @items.each do |item| %>
    <div class="post-index">
      <%= link_to item_user_path(item.user_id) do %>
        <div class="post-user-nickname-image">
          <%= image_tag item.user.image.variant(resize: '30x30'), class: "post-user-img" if item.user.image.attached? %>
          <div class="post-user-nickname"><%= item.user.nickname %></div>
        </div>
      <% end %>
      <%= link_to "#{item_path(item.id)}" do %>
        <div class="post-text-created-at">
          <div class="item-name"><%= item.name %></div>
        </div>
        <div class="item-review-star-rating">
          <% if item.reviews.present? %>
            <div class="item-review-star-front" style="width: <%= item.review_score_percentage %>%">★★★★★</div>
            <div class="item-review-star-back">★★★★★</div>
          <% end %>
        </div>
        <div class="item-review-score-average-count"><%= item.avg_score %>点(<%= item.reviews.count %>件のレビュー)</div>
        <div class="post-image">
          <%= image_tag item.image.variant(resize: '550x500'), class: "post-img" if item.image.attached? %>
        </div>
        <div class="item-text-index"><%= simple_format item.text %></div>
      <% end %>
      <div class="item-tag-box">
        <% item.tags.each do |tag| %>
          <%= link_to items_path(word: tag) do %>
            <div class="tag-item-word"><%= tag.word %></div>
          <% end %>
        <% end%>
      </div>
      <div class="action-menu">
        <% if user_signed_in? %>
          <% if current_user.id == item.user_id %>
            <div class="action-edit-item">
              <%= link_to edit_item_path(item), method: :get,class:"show-action-item-edit" do %>
                <i class="fas fa-tag"></i>
                タグを編集
              <% end %>
            </div>
            <%= link_to  item_path(item.id), method: :delete do %>
              <div class="action-destroy">
                <i class="far fa-trash-alt"></i>
                削除
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_list_likes.html.erb
<div class="list-posts">
  <% @like_posts.each do |post| %>
    <div class="post-index">
      <%= link_to user_path(post.user_id) do %>
        <div class="post-user-nickname-image">
          <%= image_tag post.user.image.variant(resize: '50x40'), class: "post-user-img" if post.user.image.attached? %>
          <div class="post-user-nickname"><%= post.user.nickname %></div>
        </div>
      <% end %>
      <%= link_to "#{post_path(post.id)}" do %>
        <div class="post-text-created-at">
          <div class="post-text"><%= post.text %></div>
          <div class="post-created-at"><%= l post.created_at %></div>
        </div>
        <div class="post-image">
          <%= image_tag post.image.variant(resize: '550x500'), class: "post-img" if post.image.attached? %>
        </div>
      <% end %>
      <div class="action-menu">
        <% if user_signed_in? %>
          <div id="like-of-<%= post.id %>">
            <%= render partial: "likes/favorite", locals: { post: post } %>
          </div>
          <% if current_user.id == post.user_id %>
            <%= link_to edit_post_path(post.id),method: :get do %>
              <div class="action-edit">
                <i class="far fa-edit"></i>
                編集
              </div>
            <% end %>
            <%= link_to  post_path(post.id), method: :delete do %>
              <div class="action-destroy">
                <i class="far fa-trash-alt"></i>
                削除
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_list_posts.html.erb
<div class="list-posts">
  <% @posts.each do |post| %>
    <div class="post-index">
      <%= link_to user_path(post.user_id) do %>
        <div class="post-user-nickname-image">
          <%= image_tag post.user.image.variant(resize: '50x40'), class: "post-user-img" if post.user.image.attached? %>
          <div class="post-user-nickname"><%= post.user.nickname %></div>
        </div>
      <% end %>
      <%= link_to "#{post_path(post.id)}" do %>
        <div class="post-text-created-at">
          <div class="post-text"><%= simple_format post.text %></div>
          <div class="post-created-at"><%= l post.created_at %></div>
        </div>
        <div class="post-image">
          <%= image_tag post.image.variant(resize: '550x500'), class: "post-img" if post.image.attached? %>
        </div>
      <% end %>
      <div class="action-menu">
        <% if user_signed_in? %>
          <div id="like-of-<%= post.id %>">
            <%= render partial: "likes/favorite", locals: { post: post } %>
          </div>
          <% if current_user.id == post.user_id %>
            <%= link_to edit_post_path(post.id),method: :get do %>
              <div class="action-edit">
                <i class="far fa-edit"></i>
                編集
              </div>
            <% end %>
            <%= link_to  post_path(post.id), method: :delete do %>
              <div class="action-destroy">
                <i class="far fa-trash-alt"></i>
                削除
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_posts_header.html.erb
<header>
  <div class="top-main-box">
    <div class="top-main-parent">
      <%= link_to "like-bike", root_path,method: :get, class:"header-logo-mark" %>
      <%= link_to "投稿一覧", posts_path,method: :get, class: "posts-lists" %>
      <%= link_to "アイテム一覧", items_path, class:"items-lists" %>
      <div class="seach-form-box">
        <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form-content") do |form| %>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
        <%= form.submit "検索", class: "search-btn" %>
        <% end %>
      </div>
        <% if user_signed_in? %>
          <%= link_to "新規投稿", new_post_path,method: :get,class:"posts-new-action" %>
          <%= link_to "アイテムを投稿", new_item_path, class:"items-new-action",data: {"turbolinks"=>false} %>
          <%=link_to "ログアウト",  destroy_user_session_path,method: :delete, class: "user-action-logout" %>
        <% else %>
           <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post,class:"btn-header-guest-login" %>
           <%= link_to "ログイン", new_user_session_path, class: "user-action-login" %>
           <%= link_to "ユーザー登録", new_user_registration_path,method: :get, class: "user-action-new" %>
        <% end %>
    </div>
  </div>
</header>

app/views/shared/_right_box.html.erb
<div class="right-box">
  <div class="user-profile">
    <% if user_signed_in?%>
      <div class="user-profile-menu">
        <div class="user-profile-menu-image-nickname">
          <%= image_tag current_user.image.variant(resize: '70x70'), class: "user-img" if current_user.image.attached? %>
          <%= link_to current_user.nickname, user_path(current_user.id),method: :get, class: "user-nickname" %>
        </div>
        <ul class="user-menu">
          <li>
            <div class="following-follower">
              <div class="current-user-following"><%= link_to "フォロー(#{current_user.followings.count})", following_user_path(current_user), class: "nav-link" %></div>
              <div class="current-user-follower"><%= link_to "フォロワー(#{current_user.followers.count})", followers_user_path(current_user), class: "nav-link" %></div>
            </div>
            <%= link_to edit_user_registration_path(current_user.id),method: :get do %>
              <div class="user-menu-edit-user">
              <i class="fas fa-user-edit"></i>
                <div class="user-menu-profile rb-txt">プロフィールを編集</div>
              </div>
            <% end %>
            <%= link_to user_path(current_user.id) do %>
              <div class="user-menu-edit-user">
                <i class="far fa-file"></i>
                <div class="user-menu-profile rb-txt">投稿を見る</div>
              </div>
            <% end %>
            <%= link_to item_user_path(current_user.id) do %>
              <div class="user-menu-edit-user">
                <i class="fas fa-glasses"></i>
                <div class="user-menu-profile rb-txt">アイテムを見る</div>
              </div>
            <% end %>
            <%= link_to like_user_path(current_user.id) do %>
              <div class="user-menu-edit-user">
                <i class="far fa-bookmark"></i>
                <div class="user-menu-profile rb-txt">いいねを見る</div>
              </div>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
   </div>
  <div class="measurement">
    <a href='#target_id'><i class="fas fa-angle-up fa-3x"></i></a>
  </div>
</div>