config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'posts#index'
  resources :users do
    member do
      get 'item'
      get 'like'
      get :following, :followers
    end
  end
  resources :follow_relationships, only: [:create, :destroy]
  resources :items do
    collection do
      get 'search'
    end
    collection do
      get 'locate'
    end
    resources :reviews, only: [:index,:create,:destroy]
  end
  resources :posts do
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :comments, only: [:create,:destroy,]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  has_many :item_tag_relations
  has_many :tags, through: :item_tag_relations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  with_options presence: true do
    validates :name
    validates :image
  end

  validates :name, length: { maximum: 40 }
  validates :text, length: { maximum: 150 }

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:rating).round(1).to_f
    end
  end

  def review_score_percentage
    reviews.average(:rating).round(1).to_f * 100 / 5 unless reviews.empty?
  end

  def self.locate(locate)
    if locate != ''
      Item.joins(:tags).where('text LIKE(?) OR name LIKE(?) OR word LIKE(?)', "%#{locate}%", "%#{locate}%", "%#{locate}%")
    else
      Item.all
    end
  end

  def save_tags(saveitem_tags)
    current_tags = tags.pluck(:word) unless tags.nil?
    old_tags = current_tags - saveitem_tags
    new_tags = saveitem_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(word: old_name)
    end

    new_tags.each do |new_name|
      item_tag = Tag.find_or_create_by(word: new_name)
      tags << item_tag
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    if params[:word].present?
      @tag = Tag.find(params[:word])
      @items = @tag.items.order(created_at: :desc)
    else
      @items = Item.includes(:user).order('created_at DESC')
    end
  end

  def new
    @item = ItemTag.new
  end

  def create
    @item = ItemTag.new(itemtags_params)
    if @item.valid?
      @item.save
      redirect_to items_path(@item)
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @reviews = @item.reviews.includes(:user).order('created_at DESC')
  end

  def destroy
    render root_path unless user_signed_in? && current_user.id == @item.user_id

    redirect_to items_path if @item.destroy
  end

  def search
    return nil if params[:keyword] == ''

    tag = Tag.where(['word LIKE ?', "%#{params[:keyword]}%"])
    render json: { keyword: tag }
  end

  def locate
    @items = Item.locate(params[:keyword]).includes(:user).order('created_at DESC')
  end

  def edit
    unless user_signed_in? && current_user.id == @item.user_id
      redirect_to action: :index
      nil
    end
    @tag_list = @item.tags.pluck(:word).join(' ')
  end

  def update
    tag_list = params[:item][:tag_ids].split(/[[:blank:]]+/).select(&:present?)
    if @item.update_attributes(item_params)
      @item.save_tags(tag_list)
      redirect_to @item
    else
      render 'edit'
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :text, :image).merge(user_id: current_user.id)
  end

  def itemtags_params
    params.require(:item_tag).permit(:name, :text, :image, :tag_ids).merge(user_id: current_user.id)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_items.html.erb
<div class="main-box">
  <div id='items_id'></div>
  <div class="left-box"></div>

  <div class="center-box">
    <div class="item-page-inform">アイテム一覧</div>
    <% if params[:word].present? %>
      <div class="item-tag-inform">タグ<%= "「#{@tag.word}」を含むアイテム" %></div>
    <% end %>
    <%= render "shared/list_items" %>
  </div>

  <%= render "shared/right_box" %>
</div>

app/views/items/edit.html.erb
<%= render "shared/items_header" %>
   
  <div class="item-edit-content">
  <%= render "shared/home" %>
    <div class="item-name-text-edit">
      <div class="show-item-name"><%= @item.name %></div>
      <div class="show-post-text"><%= @item.text %></div>
    </div>
    <% if @item.image.attached? %>
      <div class="show-item-image"><%= image_tag @item.image.variant(resize: '700x700'), class: "show-image" if @item.image.attached? %></div>
    <% end %>
    <div class="item-edit-form">
      <div class="items-edit-page">タグを編集</div>
      <div class="item-edit-tag">複数のタグをつける際は空白で区切って下さい</div>
      <%= form_with model: @item, local: true do |f| %>

        <%= f.text_field :tag_ids,value: @tag_list,\
        placeholder: "例: メーカー クロスバイク 2020年モデル",rows:"2",class: "edit-tag-form" %>

        <div>
          <%= f.submit '更新',class:"update-btn" %>
        </div>

      <% end %>
    </div>
   <%= render "shared/items" %>
  </div>

app/views/items/index.html.erb
<%= render "shared/items_header" %>
<%= render "items" %>

app/views/items/locate.html.erb
<%= render "shared/items_header" %>

<div class="main-box">
  <div id='items_id'></div>
  <div class="left-box"></div>

  <div class="center-box">
    <div class="contents-row">
      <p class="seacrh-results">
        <%= "#{params[:keyword]}の検索結果"%>
      </p>
    </div>
    <div class="item-page-inform">アイテム一覧</div>
    <%= render "shared/list_items" %>
  </div>
  <%= render "shared/right_box" %>
</div>
<%= link_to items_path do %>
  <p class="back-home-btn">
    <i class="fas fa-arrow-left"></i>
    アイテム一覧に戻る
  </p>
<% end %>

app/views/items/new.html.erb
<% content_for(:body_attributes) do %>
  data-turbolinks="false"
<% end %>

<%= render "shared/items_header" %>

<div class="new-item-box">
  <%= render "shared/home" %>
  <div class="new-item-form">
    <%= form_with model: @item, url: items_path, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="item-text-box">
        <div class="item-comment-sentence">名前</div>
        <div class="item-comment-note">必須</div>
      </div>
        <%= f.text_area :name, class: "name-box", placeholder:"※最大40字まで", maxlength:"40",rows: "3" %>
      
      <div class="item-text-box">
        <div class="item-comment-sentence">コメント</div>
        <div class="item-comment-note-any">任意</div>
      </div>
      <%= f.text_area :text, class: "text-content", placeholder:"※最大150字まで", maxlength:"150" %>
      
      <div class="item-text-box">
        <i class="fas fa-camera fa-2x"></i>
        <div class="item-comment-sentence">画像</div>
        <div class="item-comment-note">必須</div>
      </div>
      
      <div class="click-upload">
        <p class="item-comment-sentence">クリックしてファイルをアップロード</p>
        <%= f.file_field :image, class: "item-image" %>
      </div>


      <div class="item-new-tag-box">
        <i class="fas fa-tag"></i>
        <div class="item-tag-sentence">タグをつける</div>
        <div class="item-comment-note-any">任意</div>
      </div>

      <div>
        <%= f.text_field :tag_ids,class: "tag-form", id:'tag-field', placeholder:"複数のタグをつける際は空白で区切って下さい。最大40字まで",rows:"2",maxlength:"40" %>
        <div id="search-result"></div>
      </div>
      <%= f.submit "投稿する",class: "post-btn" %>
    <% end %>
  </div>
  <%= link_to items_path do %>
    <p class="back-home-btn">
      <i class="fas fa-arrow-left"></i>
      アイテム一覧に戻る
    </p>
  <% end %>
</div>

app/views/items/show.html.erb
<%= render "shared/items_header" %>

<div class="item-show-box">
  <div class="show-item-content">
    <%= render "shared/home" %>
    <div class="show-user-name"><%= link_to @item.user.nickname,item_user_path(@item.user_id),class:"show-user-nickname" %></div>
    <div class="item-show-post-text-created-at">
      <div class="show-item-name"><%= @item.name %></div>
      <div class="show-post-text"><%= @item.text %></div>
      <div class="item-show-post-created-at"><%= l @item.created_at %></div>
      <div class="show-item-tag-box">
        <% @item.tags.each do |tag| %>
          <%= link_to items_path(word: tag) do %>
          <div class="show-item-tag-word"><%= tag.word %></div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="review-text-box">アイテムの評価
    <div class="star-rating-parent">
      <% if @item.reviews.present? %>
        <div class="star-rating-front" style="width: <%= @item.review_score_percentage %>%">★★★★★</div>
        <div class="star-rating-back">★★★★★</div>
      <% end %>
    </div>
    <div class="review-score-average-count"><%= @item.avg_score %>点(<%= @item.reviews.count %>件のレビュー)</div>
  </div>
  
  <div class="show-item-image"><%= image_tag @item.image.variant(resize: '700x700'), class: "show-image" if @item.image.attached? %></div>
           
  <div class="show-action-item-menu">
    <% if user_signed_in? %>
      <% if current_user.id == @item.user_id %>
        <div class="show-action-item-edit">
          <%= link_to edit_item_path(@item), method: :get,class:"show-action-item-edit" do %>
            <i class="fas fa-tag"></i>
            タグを編集
          <% end %>
        </div>
        <div class="show-action-item-destroy">
          <%= link_to item_path(@item.id), method: :delete,class:"show-action-item-destroy"  do %>
            <i class="far fa-trash-alt"></i>
            削除
          <% end %>
        </div>
      <% end %>
     <% end %>
  </div>

  <%= render "shared/items" %>

  <%= render "reviews/form", review: @review, item: @item %>

  <div class="review-list-box">
    <i class="far fa-comment-dots"></i>
    <h4 class="review-list">レビューの一覧</h4>
  </div>

  <div class="reviews-box">
    <% if @reviews.present? %>
      <% @reviews.each do |review| %>
        <div class="reviews-index">
          <div class="review-rating-user-nickname">
            <div class="review-ratign-star"><span class="review-rating-star">★</span><%= review.rating %></div>
            <%= link_to item_user_path(review.user_id) do %>
              <div class="review-user-nickname"><%= review.user.nickname %></div>
            <% end %>
          </div>
          <div class="review-item-text"><%= simple_format review.text %></div>
          <% if user_signed_in? %>
            <% if current_user.id == review.user_id %>
              <div class="reviews-destroy-action">
                <%= link_to item_review_path(review.item.id, review.id),method: :delete,class:"reviews-destroy-action" do %>
                  <i class="fas fa-trash-alt"></i>
                  レビューを削除
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= render "shared/home" %>
</div>