config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
   }
  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'posts#index'
  resources :users do
    member do
      get 'item'
      get 'like'
      get :following, :followers
    end
  end
  resources :follow_relationships, only: [:create, :destroy]
  resources :items do
    collection do
      get 'search'
    end
    collection do
      get 'locate'
    end
    resources :reviews, only: [:index,:create,:destroy]
  end
  resources :posts do
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :comments, only: [:create,:destroy,]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :text, length: { maximum: 150 }
  validates :text, presence: true, unless: :was_attached?

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def was_attached?
    image.attached?
  end

  def self.search(search)
    if search != ''
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_post, only: [:edit, :show, :update, :destroy]

  def index
    @posts = Post.includes(:user).order('created_at DESC')
    @like = Like.new
    @likes = Like.where(post_id: params[:post_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to root_path(@post)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order('created_at DESC')
    @like = Like.new
    @likes = Like.where(post_id: params[:post_id])
  end

  def destroy
    render :index unless user_signed_in? && current_user.id == @post.user_id
    redirect_to root_path if @post.destroy
  end

  def edit
    unless user_signed_in? && current_user.id == @post.user_id
      redirect_to action: :index
      nil
    end
  end

  def update
    if @post.update(post_params)
      redirect_to root_path(@item_id)
    else
      render :edit
    end
  end

  def search
    @posts = Post.search(params[:keyword]).includes(:user).order('created_at DESC')
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:text, :image).merge(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_content.html.erb
<div class="main-box">
  <div id='target_id'></div>
  <div class="left-box"></div>

  <div class="center-box">
    <div class="post-page-inform">投稿一覧</div>
    <%= render "shared/list_posts" %>
  </div>
  <%= render "shared/right_box" %>
</div>

app/views/posts/edit.html.erb
<%= render "shared/posts_header" %>

<div class="edit-content">
  <%= render "shared/home" %>
  <div class="edit-form">
    <%= form_with model: @post, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <div class="text-box">
        <p class="comment-sentence">コメント</P>
        <%= f.text_area :text, class: "text-content", placeholder:"※最大150字まで", maxlength:"150" %>
      </div>

      <div class="click-upload">
        <div class="img-upload">
          <i class="fas fa-camera fa-2x"></i>
          <div class="img-text">画像</div>
        </div>
        <p class="comment-sentence">クリックしてファイルをアップロード</p>
        <%= f.file_field :image, class: "item-image" %>
      </div>
      <%= f.submit "変更する" ,class:"update-btn" %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<%= render "shared/posts_header" %>
<%= render "content" %>

app/views/posts/new.html.erb
<%= render "shared/posts_header" %>

<div class="new-box">
  <%= render "shared/home" %>
  <div class="new-post-form">
    <%= form_with model: @post, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
        <div class="text-box">
          <p class="comment-sentence">コメント</P>
          <%= f.text_area :text, class: "text-content", placeholder:"※最大150字まで", maxlength:"150",rows:"5" %>
        </div>
        <div class="img-upload">
          <i class="fas fa-camera fa-2x"></i>
          <div class="img-text">画像</div>
        </div>
      <div class="click-upload">
        <div class="comment-sentence">クリックしてファイルをアップロード</div>
        <%= f.file_field :image, class: "item-image" %>
      </div>
      <%= f.submit "投稿する",class: "post-btn" %>
      <%= link_to root_path do %>
        <p class="back-home-btn">
          <i class="fas fa-arrow-left"></i>
          戻る
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<%= render "shared/posts_header" %>

<div class="main-box">
  <div id='target_id'></div>
  <div class="left-box"></div>

  <div class="center-box">
    <div class="contents-row">
      <p class="seacrh-results"><%= "#{params[:keyword]}の検索結果"%></p>
    </div>
    <div class="post-page-inform">投稿一覧</div>
    <%= render "shared/list_posts" %>
  </div>
  <%= render "shared/right_box" %>
</div>
<%= render "shared/home" %>

app/views/posts/show.html.erb
<%= render "shared/posts_header" %>

<div class="show-box">
  <div class="show-content">
    <%= render "shared/home" %>
    <div class="show-user-name"><%= link_to @post.user.nickname,user_path(@post.user_id),class:"show-user-nickname" %></div>
    <div class="show-post-text-created-at">
      <div class="show-post-text"><%= @post.text %></div>
      <div class="show-post-created-at"><%= l @post.created_at %></div>
    </div>
  </div>
  <% if @post.image.attached? %>
    <div class="show-post-image"><%= image_tag @post.image.variant(resize: '700x700'), class: "show-image"  %></div>
  <% end %>
  <div class="show-action-menu">
    <div id="like-of-<%= @post.id %>">
      <%= render partial: "likes/like", locals: { post: @post } %>
    </div>
    <% if user_signed_in? %>
      <% if current_user.id == @post.user_id %>
        <%= link_to edit_post_path(@post.id),method: :get do %>
          <div class="show-action-edit-btn">
            <i class="far fa-edit"></i>
            編集
          </div>
        <% end %>
        <%= link_to post_path(@post.id), method: :delete do %>
          <div class="show-action-destroy">
            <i class="fas fa-trash-alt"></i>
            削除
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  
  <% if user_signed_in? %>
    <div class="show-action-comment">
      <div class="comment-text-info">
        <i class="far fa-comment fa-lg"></i>
        コメントを送る
      </div>
        <%= form_with(model: [@post,@comment], local: true) do |f| %> 
          <%= render 'shared/error_messages', model: f.object %>
          <%= f.text_area :text, class: "comment-area",placeholder: "(最大150字)", rows: "5", maxlength:"150" %>
            <div class="img-upload">
              <i class="fas fa-camera fa-2x"></i>
              <div class="img-text">画像</div>
            </div>
          <div class="click-upload">
            <p class="comment-sentence">クリックしてファイルをアップロード</p>
            <%= f.file_field :image, class: "item-image" %>
          </div>    
          <%= f.submit "コメントをする",class:"comment-send" %>
        <% end %>
    </div>
  <% end %>

  <div class="show-commnet-lists">
    <i class="far fa-comment-dots"></i>
    <h4 class="comments-list">コメント一覧</h4>
  </div>

  <div class="comment-index">
    <% if @comments.present? %>
      <% @comments.each do |comment| %>
        <div class="comment-box">
          <%= link_to "/users/#{comment.user_id}" do %>
            <div class="comment-image-nickname">
              <div class="comment-user-image"><%= image_tag comment.user.image.variant(resize: '30x30'),class: "comment-image" if comment.user.image.attached? %></div>
              <div class="comment-user-nickname"><%= comment.user.nickname %></div>
            </div>
          <% end %>
          <div class="comment-created-at"><%= l comment.created_at %></div>
          <div class="comment-text"><%= comment.text %></div>
          <div class="image-text-align"><%= image_tag comment.image.variant(resize: '300x300'), class: "comment-image" if comment.image.attached? %></div>
          <% if user_signed_in? %>
            <% if current_user.id == comment.user.id %>
              <div class="comment-destroy">
                <%= link_to  post_comment_path(comment.post.id, comment.id),method: :delete,class:"comment-destroy-btn" do %>
                  <i class="fas fa-trash-alt"></i>
                  削除する
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end%>
  </div> 
  <%= render "shared/home" %>
</div>